RedisConfiguration:
    host: "127.0.0.1"
    port: 6379
    username: "default"
    password: ""
    topic: "dungeons:packets" #Don't change or know what you're doing

DatabaseConfiguration:
    type: "mysql" #Supported types: mongodb, mysql

    mysql:
        host: "localhost"
        port: 3306
        database: "dungeons"
        username: "root"
        password: "root"

    mongodb:
        host: "localhost"
        port: 27017
        database: "dungeons"

ServerConfiguration:
    isLobby: true
    banCommand: "litebans:ban {player} {time} {reason}"