PluginConfiguration:

ASWMConfiguration:
  # The loader be used to load and save the world (file, mysql, mongodb)
  Loader: "file"
  LoaderConfiguration:
    host: "localhost"
    port: 3306
    useSSL: false
    user: "dungeons"
    password: "dungeons"
    database: "dungeons"