RedisConfiguration:
    host: "127.0.0.1"
    port: 6379
    username: "default"
    password: ""
    topic: "dungeons:packets" #Don't change or know what you're doing

ServerConfiguration:
    isLobby: true